theme:
  name: 'material'
  logo: images/plain_logo14.png
  favicon: images/favicon.ico
site_name: Imposter Mocks

plugins:
  - search
  - mermaid2

extra:
  analytics:
    provider: google
    property: G-K7GTJGJQ2S

nav:
  - Introduction: 'index.md'
  - Getting started: 'getting_started.md'

  - Core concepts:
    - Configuration guide: 'configuration.md'
    - Response templates: 'templates.md'
    - Scripting: 'scripting.md'
    - Security: 'security.md'
    - Steps: 'steps.md'
  
  - Mock types:
    - OpenAPI (and Swagger): 'openapi_plugin.md'
    - REST: 'rest_plugin.md'
    - SOAP (and WSDL): 'soap_plugin.md'
    - HBase: 'hbase_plugin.md'
    - SFDC (Salesforce): 'sfdc_plugin.md'
    - WireMock: 'wiremock_plugin.md'

  - Developing mocks:
    - Advanced request matching: 'request_matching.md'
    - Interceptors: 'interceptors.md'
    - OpenAPI validation: 'openapi_validation.md'
    - Template queries: 'template_queries.md'
    - Directory-based responses: 'directory_responses.md'
    - Performance simulation: 'performance_simulation.md'
    - Failure simulation: 'failure_simulation.md'
    - Generating fake data: 'fake_data.md'
    - CORS: 'cors.md'
    - Groovy scripting tips: 'groovy_tips.md'
    - JavaScript compatibility: 'scripting_modern_js.md'
    - Examples: 'https://github.com/outofcoffee/imposter/tree/main/examples'

  - Data capture and storage:
    - Data capture: 'data_capture.md'
    - Stores: 'stores.md'
    - GraphQL: 'stores_graphql.md'

  - Configuration:
    - Configuration guide: 'configuration.md'
    - Configuration location: 'config_location.md'
    - Scaffolding configuration: 'scaffold.md'
    - Environment variables: 'environment_variables.md'
    - Proxy an existing endpoint: 'proxy_endpoint.md'
    - Recursive configuration discovery: 'config_discovery.md'
    - Bundling configuration: 'bundle.md'
  
  - Run and deploy:
    - 'Command line (CLI)': 'run_imposter_cli.md'
    - Docker: 'run_imposter_docker.md'
    - AWS Lambda: 'run_imposter_aws_lambda.md'
    - Java JAR file: 'run_imposter_jar.md'
    - Deployment patterns: 'deployment_patterns.md'
    - Running in GitHub Actions: 'github_actions.md'
    
  - Operational topics:
    - Metrics, health, logs and telemetry: 'metrics_logs_telemetry.md'
    - Performance tuning: 'performance_tuning.md'
    - Benchmarks: 'benchmarks.md'
    - TLS/SSL: 'tls_ssl.md'

  - Other:
    - Plugins: 'plugins.md'
    - Features: 'features.md'
    - Tips and tricks: 'tips_tricks.md'
    - Usage: 'usage.md'

  - Product:
    - Summary: 'summary.md'
    - Home: 'https://www.imposter.sh'

  - Tutorials:
    - Mocking APIs with OpenAPI and Imposter: 'https://medium.com/@outofcoffee/mocking-apis-with-swagger-and-imposter-3694bd1733c0'
    - Mocking REST APIs with Imposter: 'https://medium.com/@outofcoffee/mocking-apis-with-imposter-53bd908632e5'
    - Mocking SOAP web services with Imposter: 'https://medium.com/@outofcoffee/mocking-soap-web-services-with-imposter-da8e9666b5b4'
  
  - Developers:
    - GitHub: 'https://github.com/outofcoffee/imposter'
    - Roadmap: 'roadmap.md'
    - Build: 'build.md'
