theme:
  name: 'material'
  logo: images/plain_logo14.png
  favicon: images/favicon.ico
site_name: Imposter Mocks

extra:
  analytics:
    provider: google
    property: G-K7GTJGJQ2S

nav:
  - Home: 'https://www.imposter.sh'
  - Introduction: 'index.md'
  - Getting started: 'getting_started.md'
  - Configuration guide: 'configuration.md'
  - Response templates: 'templates.md'
  - Scripting: 'scripting.md'
  - Security: 'security.md'

  - Mock types:
    - OpenAPI (and Swagger): 'openapi_plugin.md'
    - REST: 'rest_plugin.md'
    - SOAP (and WSDL): 'soap_plugin.md'
    - HBase: 'hbase_plugin.md'
    - SFDC (Salesforce): 'sfdc_plugin.md'
    - WireMock: 'wiremock_plugin.md'

  - Data capture and storage:
    - Data capture: 'data_capture.md'
    - Stores: 'stores.md'
    - GraphQL: 'stores_graphql.md'

  - Operational topics:
    - Metrics, logs and telemetry: 'metrics_logs_telemetry.md'
    - Performance tuning: 'performance_tuning.md'
    - Benchmarks: 'benchmarks.md'
    - TLS/SSL: 'tls_ssl.md'
    - Usage (arguments and environment variables): 'usage.md'

  - Advanced:
    - Advanced request matching: 'request_matching.md'
    - OpenAPI validation: 'openapi_validation.md'
    - Template queries: 'template_queries.md'
    - Performance simulation: 'performance_simulation.md'
    - Failure simulation: 'failure_simulation.md'
    - Proxy an existing endpoint: 'proxy_endpoint.md'
    - Scaffolding configuration: 'scaffold.md'
    - Fake data: 'fake_data.md'
    - CORS: 'cors.md'
    - Groovy scripting tips: 'groovy_tips.md'

  - Other:
    - Plugins: 'plugins.md'
    - Features: 'features.md'
    - Tips and tricks: 'tips_tricks.md'

  - Developers:
    - GitHub: 'https://github.com/outofcoffee/imposter'
    - Roadmap: 'roadmap.md'
    - Build: 'build.md'

  - Tutorials:
    - Mocking APIs with OpenAPI and Imposter: 'https://medium.com/@outofcoffee/mocking-apis-with-swagger-and-imposter-3694bd1733c0'
    - Mocking REST APIs with Imposter: 'https://medium.com/@outofcoffee/mocking-apis-with-imposter-53bd908632e5'
    - Mocking SOAP web services with Imposter: 'https://medium.com/@outofcoffee/mocking-soap-web-services-with-imposter-da8e9666b5b4'
