---
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-cache

      - run:
          name: Fetch dependencies
          command: ./gradlew dependencies --refresh-dependencies

      - run:
          name: Run gradle build
          command: ./gradlew test shadowJar --info --stacktrace

      - run:
          name: Publish maven artifacts
          command: ./gradlew publish --info --stacktrace

      - save_cache:
          key: gradle-cache
          paths:
            - ~/.gradle

      - save_cache:
          key: artifacts-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - distro/build/libs
            - docker
            - scripts

  deploy:
    docker:
      - image: circleci/openjdk:8
    steps:
      - restore_cache:
          keys:
            - artifacts-{{ .Environment.CIRCLE_SHA1 }}

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and push Docker image
          command: |
            chmod +x ./scripts/*.sh

            IMAGE_TAG_NAME="$( ./scripts/branch-to-tag-name.sh ${CIRCLE_BRANCH} )"
            if [[ ! -z ${IMAGE_TAG_NAME} ]]; then
              ./scripts/docker-build.sh "${IMAGE_TAG_NAME}"
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
               - master
               - develop
