name: CI on push
on: [ push ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      effective-branch: ${{ steps.git-meta.outputs.EFFECTIVE_BRANCH }}
      release: ${{ startsWith(github.ref, 'refs/tags/') }}
      version: ${{ steps.git-meta.outputs.CURRENT_VERSION }}
    env:
      SINCE_VERSION: "0.15.5"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install since
        run: |
          cd "$( mktemp -d )"
          curl --fail -L -o since.tar.gz https://github.com/release-tools/since/releases/download/v${SINCE_VERSION}/since_${SINCE_VERSION}_linux_amd64.tar.gz
          tar xvf since.tar.gz
          cp since /usr/local/bin

      - name: Determine effective branch
        id: git-meta
        run: |
          echo "EFFECTIVE_BRANCH=$( ./scripts/get-effective-branch.sh )" >> $GITHUB_OUTPUT
          echo "CURRENT_VERSION=$( since project version --current )" >> $GITHUB_OUTPUT

  ci:
    needs: [setup]
    uses: ./.github/workflows/ci.yaml
    with:
      effective-branch: ${{ needs.setup.outputs.effective-branch }}
      release: ${{ needs.setup.outputs.release == 'true' }}
      version: ${{ needs.setup.outputs.version }}
    secrets: inherit
